env:
  matrix:
    - LWS_METHOD=default CMAKE_ARGS=""

os:
  - linux
  - osx

language: generic

install: if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq ; sudo apt-get install -y -qq libgit2-0 libgit2-dev libarchive13 libarchive-dev ; fi ; if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install libgit2 ; fi

script: mkdir build && cd build && cmake $CMAKE_ARGS .. && cmake --build . && sudo make install

sudo: required
dist: trusty

